### ISSUE TITLE
Windows 8.1 w/ PHPStorm 9.0 build #PS-141.1912

### ISSUE THREAD

**Issue by Lammmas** [vexus2/cake-storm#27]
Tried to go to View from Controller, Controller from View, Model from Controller and SmartJump; In all cases there's the error `IllegalArgumentException: Argument for @NotNull parameter 'content' of com/intellij/notification/Notification. must not be null`.
```
Argument for @NotNull parameter 'content' of com/intellij/notification/Notification.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'content' of com/intellij/notification/Notification.<init> must not be null
	at com.intellij.notification.Notification.<init>(Notification.java)
	at com.vexus2.cakestorm.ide.Actions.notification(Actions.java:16)
	at com.vexus2.cakestorm.ide.Actions$SmartJump.actionPerformed(Actions.java:26)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:644)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:359)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:295)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:219)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vexus2** [comment]
Hi. May I Have your cakephp's versions?

**Comment by wp4nuv** [comment]
I believe it's 2.6.3
